### ISSUE TITLE
백준10828번 문제 풀이

### ISSUE THREAD

**Issue by CHOIYEJUN** [whdghk1907/Algorithm#3]
스택을 이용한 문제풀이 스탭 1

풀다가 너무 늦어서 내일 풀도록 하겠습니다 

[문제]

정수를 저장하는 스택을 구현한 다음, 입력으로 주어지는 명령을 처리하는 프로그램을 작성하시오.

명령은 총 다섯 가지이다.

push X: 정수 X를 스택에 넣는 연산이다.
pop: 스택에서 가장 위에 있는 정수를 빼고, 그 수를 출력한다. 만약 스택에 들어있는 정수가 없는 경우에는 -1을 출력한다.
size: 스택에 들어있는 정수의 개수를 출력한다.
empty: 스택이 비어있으면 1, 아니면 0을 출력한다.
top: 스택의 가장 위에 있는 정수를 출력한다. 만약 스택에 들어있는 정수가 없는 경우에는 -1을 출력한다.

```
예제 입력 2 
7
pop
top
push 123
top
pop
top
pop
```

```
예제 출력 2 
-1
-1
123
123
-1
-1
```

**Comment by whdghk1907** [comment]
해결하여 커밋 했습니다.
